import Header from "@/components/shared/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-[1200px] mx-auto">
          <Header />
        </div>
        <div className="max-w-[1200px] mx-auto">{children}</div>
        <div className="max-w-full mx-auto">
          <Footer />
        </div>
      </body>
    </html>
  );
}
